# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/r0x0d/rhc-bash-worker
%global goipath         github.com/r0x0d/rhc-bash-worker

%gometa -f

%global godocs          README.md

Name:           rhc-bash-worker
Version:        0.1
Release:        1%{?dist}
Summary:        Experimental worker for Convert2RHEL.

License:        # FIXME
URL:            %{gourl}
Source0:        %{url}/archive/v%{version}/%{name}-%{version}.tar.gz
BuildArch:      noarch

%description
Experimental worker for Convert2RHEL.

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in src; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
